version: '3.4'

services:
  chuckdevicecontroller:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro